GET http://localhost:3000/user
X-User-Id: 14

###
GET http://localhost:3000/products

###
GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzIwMjg2OTE3LCJleHAiOjE3MjAyODY5Mzd9.Q-WrHremHuKqBUUz6rybVgkXj2kg61iixF9SZzxnDUQ

###
GET http://localhost:3000/pelanggan
Content-Type: :application/json
X-User-Id: 12

###
GET http://localhost:3000/pembayaran
Content-Type: :application/json
X-User-Id: 12

###
PATCH http://localhost:3000/pelanggan/5
Content-Type: application/json
X-User-Id: 12

{
  "id_pelanggan": 6,
  "bulan": "6",
  "tahun": "2024",
  "meter_awal": 234,
  "meter_akhir": 542
}

###
POST http://localhost:3000/tarif
Content-Type: application/json

{
  "daya": "2200",
  "tarifperkwh": "1444"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "balramadan",
  "password": "balramadan"
}

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/token

###
PATCH  http://localhost:5000/users/5
Content-Type: application/json

{
  "name": "Fikal"
}
###
PATCH  http://localhost:5000/products/1
Content-Type: application/json

{
  "image": "/src/assets/product-images/ArenLatte.png",
  "title": "Aren Latte",
  "price": 29000,
  "desc": "Rasa alami gula aren berpadu sempurna dengan espresso premium",
  "category": "Signature"
}

###
DELETE  http://localhost:5000/users/2
